apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb-deployment
  namespace: smo
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template: # blueprint for pods
    metadata:
      labels:
        app: mariadb
    spec:     
      containers:
      - name: mariadb
        image: mariadb
        ports:
          - containerPort: 3306 #default one
        env:
          - name: MARIADB_ROOT_PASSWORD
            value: mudemeja
        volumeMounts:
          - name: mysql-initdb
            mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: mysql-initdb
          configMap:
            name: mysql-initdb-config
    
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-initdb-config
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS intent;
    USE intent;
    CREATE TABLE IF NOT EXISTS intent.intents (id int primary key AUTO_INCREMENT,name varchar(255),description varchar(255),ric_id varchar(255),policy_id int,service_id varchar(255),policy_type_id int);

---
apiVersion: v1
kind: Service
metadata:
  name: mariadb-service
spec:
  selector:
    app: mariadb
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
