apiVersion: apps/v1
kind: Deployment
metadata:
  name: smoapp-deployment
  namespace: smo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: smoapp
  template:
    metadata:
      labels:
        app: smoapp
    spec:
      containers:
      - name: smoapp
        image: gabiminz/intents:latest
        imagePullPolicy: Always
        ports:
        - name: smoapp-http
          containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: smoapp-service
spec:
  selector:
    app: smoapp
  ports:
    - port: 3000
      targetPort: smoapp-http