apiVersion: apps/v1
kind: Deployment
metadata:
  name: rapp
  namespace: ricrapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rapp
  template:
    metadata:
      labels:
        app: rapp
    spec:
      containers:
      - name: smoapp
        image: gabiminz/rapp:latest
        ports:
        - containerPort: 9555

---
apiVersion: v1
kind: Service
metadata:
  name: rapp-service
spec:
  selector:
    app: rapp
  ports:
    - protocol: TCP
      port:  9555
      targetPort: 9555